### ISSUE TITLE
Reactables

### ISSUE THREAD

**Issue by neuronicnobody** [dylibso/reactables#1]
- [x] Create initial repo & README
- [x] Code for Reactable Core
- [ ] Code for Reactable Email (react-email)
- [ ] Code for Reactable (react-pdf)
- [x] Finish / Polish up README
- [ ] Generic Github Action for 
- [ ] Write blog post

**Comment by bhelx** [comment]
I think we should close this to clear it out from the board. if we do want to go back and invest more into reactables we can plan and prioritize from that point.
